### PR TITLE
Add auto update Purpur commit workflow

### PR DESCRIPTION
**Pull request by HaHaWTH**
This workflow updates purpurRef automatically

### CODE REVIEW

**Review by NONPLAYT — COMMENTED** [review]
It's a good update, but there's one question: if Purpur doesn't have any new commits, then workflow just crashes. Maybe make a check if there are any new commits?

**Comment by HaHaWTH** [comment]
> It's a good update, but there's one question: if Purpur doesn't have any new commits, then workflow just crashes. Maybe make a check if there are any new commits?

Got it, added in the latest commit:)

**Comment by Pancaksee** [comment]
i made a version where you just click a button to do the workflow not automate cause im not paying that crap

**Comment by Pancaksee** [comment]
`name: Upstream
on:
  workflow_dispatch:
jobs:
  upstream:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"
      - name: Update Upstream
        run: |
          ./scripts/updateUpstream.sh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}`

**Review by NONPLAYT — APPROVED** [review]
Great, that's better. If there are patch conflicts, then I will fix them myself. Thank you for your PR

**Pull request merged**
